const Data = [
    {
        id:1,
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
        height: 100,

        },
    {
        id:2,
         text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
         userNmae:'Alisa Mike',
         time:11.53,
         images: require("../../Components/Image/user_1.jpg"),
         width: 100,
        height: 100,
        },
    {
        id:3, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    },
    {
        id:4,
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
       height: 100,
    },
    {
        id:5, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    },
    {
        id:6, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    },
    {
        id:7, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    },
    {
        id:8, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    },
    {
        id:9,
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
        },
    {
        id:10, 
        text: 'When he’s not off making one of his beautifully idiosyncratic films, the director ...',
        userNmae:'Alisa Mike',
        time:11.53,
        images: require("../../Components/Image/user_1.jpg"),
        width: 100,
         height: 100,
    }, 

    ];
export default Data;